<?php

namespace VIB\Bundle\DNAsequenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FeatureAliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureAliasRepository extends EntityRepository
{
}
