<?php

/*
 * This file is part of the BioSymfony framework.
 *
 * Copyright 2011 Radoslaw Kamil Ejsmont <radoslaw@ejsmont.net>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace VIB\Bundle\BioBundle\Repository\DNA\Feature;

use Doctrine\ORM\EntityRepository;

/**
 * VIB\Bundle\BioBundle\Repository\DNA\Feature\FeatureTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureTagRepository extends EntityRepository
{
}
